# CardEverything v5.0.0 Prometheus 配置
# 作者: Project-Manager AI Agent
# 版本: 5.0.0
# 日期: 2025-09-14

global:
  scrape_interval: 15s        # 默认抓取间隔
  evaluation_interval: 15s   # 规则评估间隔
  external_labels:
    monitor: 'cardeverything'
    environment: 'production'

# 告警规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus 自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # 应用服务监控
  - job_name: 'cardeverything-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    sample_limit: 10000
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*|process_.*'
        action: drop

  # PostgreSQL 监控
  - job_name: 'cardeverything-postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis 监控
  - job_name: 'cardeverything-redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx 监控
  - job_name: 'cardeverything-nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker 容器监控
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter 系统监控
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Blackbox 探针监控
  - job_name: 'blackbox'
    static_configs:
      - targets:
        - http://app:3000/health
        - https://www.google.com
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 60s
    scrape_timeout: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115